services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      args:
        user: ${UNIX_USER}
        uid: ${UNIX_UID}
    container_name: ${APP_NAME}-backend
    image: php:8.2
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mrdriskell-network

  frontend:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    container_name: ${APP_NAME}-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
    networks:
      - mrdriskell-network

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - mrdriskell-network

  db:
    image: mariadb:10.6.17-focal
    container_name: ${APP_NAME}-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mrdriskell-network

networks:
  mrdriskell-network:
    driver: bridge
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450